In [1]:
import argparse
import numpy as np
from data_loader import load_data

np.random.seed(555)

parser = argparse.ArgumentParser()
parser.add_argument('--dataset', type=str, default='movie', help='which dataset to use')
parser.add_argument('--dim', type=int, default=16, help='dimension of entity and relation embeddings')
parser.add_argument('--n_hop', type=int, default=1, help='maximum hops')
parser.add_argument('--kge_weight', type=float, default=0.01, help='weight of the KGE term')
parser.add_argument('--l2_weight', type=float, default=1e-7, help='weight of the l2 regularization term')
parser.add_argument('--lr', type=float, default=0.02, help='learning rate')
parser.add_argument('--batch_size', type=int, default=1024, help='batch size')
parser.add_argument('--n_epoch', type=int, default=100, help='the number of epochs')
parser.add_argument('--n_memory', type=int, default=60, help='size of ripple set for each hop')
parser.add_argument('--item_update_mode', type=str, default='plus_transform',
                    help='how to update item at the end of each hop')
parser.add_argument('--using_all_hops', type=bool, default=True,
                    help='whether using outputs of all hops or just the last hop when making prediction')



parser.add_argument('--use_cuda', type=bool, default=True, help='whether to use gpu')
args = parser.parse_args(args=[])



In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

from sklearn.metrics import roc_auc_score


class RippleNet(nn.Module):
    def __init__(self, args, n_entity, n_relation):
        super(RippleNet, self).__init__()

        self._parse_args(args, n_entity, n_relation)

        # 做Embedding 
        self.entity_emb = nn.Embedding(self.n_entity, self.dim) #n_e*dim # 从Embedding里面取数据是不会改变维度的
        self.relation_emb = nn.Embedding(self.n_relation, self.dim * self.dim) # n_r*dim*dim
        self.transform_matrix = nn.Linear(self.dim, self.dim, bias=False)  # dim*dim
        self.criterion = nn.BCELoss()

    def _parse_args(self, args, n_entity, n_relation):
        self.n_entity = n_entity
        self.n_relation = n_relation
        self.dim = args.dim
        self.n_hop = args.n_hop
        self.kge_weight = args.kge_weight
        self.l2_weight = args.l2_weight
        self.lr = args.lr
        self.n_memory = args.n_memory
        self.item_update_mode = args.item_update_mode
        self.using_all_hops = args.using_all_hops

    def forward(
        self,
        items: torch.LongTensor,  # 要预测的物品索引 注意要存在于KG里面
        labels: torch.LongTensor,
        memories_h: list,     
        memories_r: list,
        memories_t: list,
    ):
        # [batch size, dim]
        item_embeddings = self.entity_emb(items)
        h_emb_list = []
        r_emb_list = []
        t_emb_list = []
        # 从训练集中读取数据，每批次1024个
        for i in range(self.n_hop):
            # [batch size, n_memory, dim]
            h_emb_list.append(self.entity_emb(memories_h[i]))    
            # [batch size, n_memory, dim, dim]
            r_emb_list.append(
                self.relation_emb(memories_r[i]).view(
                    -1, self.n_memory, self.dim, self.dim      
                )
            )
            # [batch size, n_memory, dim]
            t_emb_list.append(self.entity_emb(memories_t[i]))

        o_list, item_embeddings = self._key_addressing(
            h_emb_list, r_emb_list, t_emb_list, item_embeddings
        )
        scores = self.predict(item_embeddings, o_list)

        return_dict = self._compute_loss(
            scores, labels, h_emb_list, t_emb_list, r_emb_list
        )
        return_dict["scores"] = scores

        return return_dict

    def _compute_loss(self, scores, labels, h_emb_list, t_emb_list, r_emb_list):
        base_loss = self.criterion(scores, labels.float())

        kge_loss = 0
        for hop in range(self.n_hop):
            # [batch size, n_memory, 1, dim]
            h_expanded = torch.unsqueeze(h_emb_list[hop], dim=2)
            # [batch size, n_memory, dim, 1]
            t_expanded = torch.unsqueeze(t_emb_list[hop], dim=3)
            # [batch size, n_memory, dim, dim]
            hRt = torch.squeeze(
                torch.matmul(torch.matmul(h_expanded, r_emb_list[hop]), t_expanded)
            )
            kge_loss += torch.sigmoid(hRt).mean()
        kge_loss = -self.kge_weight * kge_loss

        l2_loss = 0
        for hop in range(self.n_hop):
            l2_loss += (h_emb_list[hop] * h_emb_list[hop]).sum()
            l2_loss += (t_emb_list[hop] * t_emb_list[hop]).sum()
            l2_loss += (r_emb_list[hop] * r_emb_list[hop]).sum()
        l2_loss = self.l2_weight * l2_loss

        loss = base_loss + kge_loss + l2_loss
        return dict(base_loss=base_loss, kge_loss=kge_loss, l2_loss=l2_loss, loss=loss)

    # h_emb_list [n_hop, batch size, n_memory, dim]
    # r_emb_list [n_hop, batch size, n_memory, dim, dim]
    # t_emb_list [n_hop, batch size, n_memory, dim]
    def _key_addressing(self, h_emb_list, r_emb_list, t_emb_list, item_embeddings):
        o_list = []
        for hop in range(self.n_hop):
            # [batch_size, n_memory, dim, 1]
            h_expanded = torch.unsqueeze(h_emb_list[hop], dim=3)
            
            # [batch_size, n_memory, dim] 32*16
            Rh = torch.squeeze(torch.matmul(r_emb_list[hop], h_expanded))
            
            # [batch_size, dim, 1]  16*1
            v = torch.unsqueeze(item_embeddings, dim=2)
            
            # [batch_size, n_memory]
            probs = torch.squeeze(torch.matmul(Rh, v))
            
            # [batch_size, n_memory]
            probs_normalized = F.softmax(probs, dim=1)
            
            # [batch_size, n_memory, 1]
            probs_expanded = torch.unsqueeze(probs_normalized, dim=2)
            
            # [batch_size, dim]
            o = (t_emb_list[hop] * probs_expanded).sum(dim=1)
            
            item_embeddings = self._update_item_embedding(item_embeddings, o)
            o_list.append(o)
        return o_list, item_embeddings

    def _update_item_embedding(self, item_embeddings, o):
        if self.item_update_mode == "replace":
            item_embeddings = o
        elif self.item_update_mode == "plus":
            item_embeddings = item_embeddings + o
        elif self.item_update_mode == "replace_transform":
            item_embeddings = self.transform_matrix(o)
        elif self.item_update_mode == "plus_transform":
            item_embeddings = self.transform_matrix(item_embeddings + o)
        else:
            raise Exception("Unknown item updating mode: " + self.item_update_mode)
        return item_embeddings

    def predict(self, item_embeddings, o_list):
        y = o_list[-1]
        if self.using_all_hops:
            for i in range(self.n_hop - 1):
                y += o_list[i]

        # [batch_size]
        scores = (item_embeddings * y).sum(dim=1)
        return torch.sigmoid(scores)

    def evaluate(self, items, labels, memories_h, memories_r, memories_t):
        return_dict = self.forward(items, labels, memories_h, memories_r, memories_t)
        scores = return_dict["scores"].detach().cpu().numpy()
        labels = labels.cpu().numpy()
        auc = roc_auc_score(y_true=labels, y_score=scores)
        predictions = [1 if i >= 0.5 else 0 for i in scores]
        acc = np.mean(np.equal(predictions, labels))
        return auc, acc


In [4]:
import numpy as np
import torch



def train(args, data_info, show_loss):
    train_data = data_info[0]
    eval_data = data_info[1]
    test_data = data_info[2]
    n_entity = data_info[3]
    n_relation = data_info[4]
    ripple_set = data_info[5]

    model = RippleNet(args, n_entity, n_relation)
    if args.use_cuda:
        model.cuda()
    optimizer = torch.optim.Adam(
        filter(lambda p: p.requires_grad, model.parameters()),
        args.lr,
    )

    for step in range(args.n_epoch):
        # training
        np.random.shuffle(train_data)
        start = 0
        while start < train_data.shape[0]:
            return_dict = model(*get_feed_dict(args, model, train_data, ripple_set, start, start + args.batch_size))
            loss = return_dict["loss"]

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            start += args.batch_size
            if show_loss:
                print('%.1f%% %.4f' % (start / train_data.shape[0] * 100, loss.item()))

        # evaluation
        train_auc, train_acc = evaluation(args, model, train_data, ripple_set, args.batch_size)
        eval_auc, eval_acc = evaluation(args, model, eval_data, ripple_set, args.batch_size)
        test_auc, test_acc = evaluation(args, model, test_data, ripple_set, args.batch_size)

        print('epoch %d    train auc: %.4f  acc: %.4f    eval auc: %.4f  acc: %.4f    test auc: %.4f  acc: %.4f'
                % (step, train_auc, train_acc, eval_auc, eval_acc, test_auc, test_acc))
    # 保存模型
    torch.save(model.state_dict(), '../models/ripple100.pth') 
    net_args = []
    net_args.append(n_entity)
    net_args.append(n_relation)
    np.save('../models/net_args.npy', net_args)


# data: [[user, item, rate]...]
def get_feed_dict(args, model, data, ripple_set, start, end):
    items = torch.LongTensor(data[start:end, 1])  # 一维 [item1, item2...]
    labels = torch.LongTensor(data[start:end, 2])  # 一维
    memories_h, memories_r, memories_t = [], [], []
    # memories_h:
    # [[h1, h2,...],  第1层的所有头节点
    #  [...]...]      第2层..
    for i in range(args.n_hop):
        memories_h.append(torch.LongTensor([ripple_set[user][i][0] for user in data[start:end, 0]]))
        memories_r.append(torch.LongTensor([ripple_set[user][i][1] for user in data[start:end, 0]]))
        memories_t.append(torch.LongTensor([ripple_set[user][i][2] for user in data[start:end, 0]]))
    if args.use_cuda:
        items = items.cuda()
        labels = labels.cuda()
        memories_h = list(map(lambda x: x.cuda(), memories_h))
        memories_r = list(map(lambda x: x.cuda(), memories_r))
        memories_t = list(map(lambda x: x.cuda(), memories_t))
    return items, labels, memories_h, memories_r,memories_t


def evaluation(args, model, data, ripple_set, batch_size):
    start = 0
    auc_list = []
    acc_list = []
    model.eval()
    while start < data.shape[0]:
        auc, acc = model.evaluate(*get_feed_dict(args, model, data, ripple_set, start, start + batch_size))
        auc_list.append(auc)
        acc_list.append(acc)
        start += batch_size
    model.train()
    return float(np.mean(auc_list)), float(np.mean(acc_list))


In [6]:
show_loss = False
data_info = load_data(args)  # train_data, eval_data, test_data, n_entity, n_relation, ripple_set
ripple_set = data_info[5]
np.save('../models/ripple_set.npy', ripple_set)
np.save('../models/train_data.npy', data_info[0])
train(args, data_info, show_loss)


reading rating file ...
splitting dataset ...
reading KG file ...
constructing knowledge graph ...
constructing ripple set ...
epoch 0    train auc: 0.5592  acc: 0.5308    eval auc: 0.5180  acc: 0.5131    test auc: 0.5187  acc: 0.4969
epoch 1    train auc: 0.6343  acc: 0.5758    eval auc: 0.5375  acc: 0.5173    test auc: 0.5253  acc: 0.4969
epoch 2    train auc: 0.6838  acc: 0.6045    eval auc: 0.5433  acc: 0.5152    test auc: 0.5318  acc: 0.5114
epoch 3    train auc: 0.7160  acc: 0.6348    eval auc: 0.5505  acc: 0.5277    test auc: 0.5319  acc: 0.5198
epoch 4    train auc: 0.7394  acc: 0.6503    eval auc: 0.5554  acc: 0.5267    test auc: 0.5316  acc: 0.5218
epoch 5    train auc: 0.7560  acc: 0.6697    eval auc: 0.5557  acc: 0.5236    test auc: 0.5343  acc: 0.5146
epoch 6    train auc: 0.7768  acc: 0.6835    eval auc: 0.5542  acc: 0.5257    test auc: 0.5395  acc: 0.5104
epoch 7    train auc: 0.7969  acc: 0.7047    eval auc: 0.5551  acc: 0.5277    test auc: 0.5428  acc: 0.5166
epoch 8  

# Predict

In [30]:
net_args = np.load('../models/net_args.npy')
ripple_set = np.load('../models/ripple_set.npy', allow_pickle=True
).item()

model = RippleNet(args, net_args[0], net_args[1])
if args.use_cuda:
    model.cuda()
model.load_state_dict(torch.load('../models/ripple100.pth')) # 加载模型的权重
model.eval() # 将模型设置为评估模式

RippleNet(
  (entity_emb): Embedding(591, 16)
  (relation_emb): Embedding(1, 256)
  (transform_matrix): Linear(in_features=16, out_features=16, bias=False)
  (criterion): BCELoss()
)

In [11]:
ripple_set

array(defaultdict(<class 'list'>, {0: [([286, 184, 441, 286, 335, 349, 184, 335, 55, 349, 349, 140, 140, 55, 184, 55, 184, 113, 184, 335, 335, 113, 113, 286, 55, 55, 286, 140, 286, 286, 140, 140], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [44, 18, 16, 279, 56, 30, 7, 313, 76, 87, 357, 19, 117, 95, 156, 1, 167, 54, 176, 55, 35, 55, 89, 262, 108, 41, 275, 127, 37, 145, 60, 126]), ([55, 56, 37, 37, 55, 56, 55, 55, 55, 37, 55, 55, 55, 56, 37, 55, 55, 55, 56, 56, 56, 56, 37, 55, 55, 37, 37, 55, 55, 56, 37, 37], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [16, 37, 174, 33, 1, 7, 86, 102, 91, 151, 96, 75, 105, 266, 55, 68, 105, 99, 263, 258, 254, 44, 60, 72, 102, 156, 170, 99, 19, 19, 76, 182])], 1: [([336, 372, 115, 336, 442, 115, 372, 372, 115, 115, 47, 372, 372, 115, 372, 442, 115, 372, 115, 442, 71, 115, 442, 71, 372, 71, 336, 71, 442, 442, 47, 115], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [31]:
import pandas as pd
# 读取已保存的item_index.txt文件，并构建item_index_dict字典

def load_item_index(file_path):
    item_index_df = pd.read_csv(file_path, sep="\t")
    item_index_dict = dict(zip(item_index_df["item"], item_index_df["index"]))
    return item_index_dict, item_index_df

# 定义文件路径
saved_item_index_path = "../process/item_index.txt"

# 尝试加载已保存的item_index.txt文件
try:
    item_index_dict, item_index_df = load_item_index(saved_item_index_path)
    print("Item index loaded successfully.")
except FileNotFoundError:
    print("Item index file not found. You may need to create it.")

# 然后可以使用get_item_or_index函数
def get_item_or_index(x):
    # 如果输入的是item名，就返回索引值
    if isinstance(x, str):
        return item_index_dict.get(x, None)
    # 如果输入的是索引值，就返回item名
    elif isinstance(x, int):
        return item_index_df.loc[item_index_df["index"] == x, "item"].values[0]
    # 否则，返回None
    else:
        return None


Item index loaded successfully.


In [6]:
print(get_item_or_index('前端开发'))

496


In [45]:
import numpy as np
data = np.array([[1,2,3],[3,4,5]])
data[:, 0]

array([1, 3])

In [11]:
model.entity_emb(items).shape
# model.entity_emb(labels).shape

NameError: name 'items' is not defined

In [30]:
route_index = get_item_or_index('前端开发')
data = np.array([[0, route_index, 0]])
ripple_set = data_info[5]
route_index

496

In [55]:
train_data = data_info[0]
print(train_data)
print(train_data[0:2, 1])

print(torch.LongTensor(train_data[0:2, 1]))

# hop=0  h 前两个user的rippleset第0层
[ripple_set[user][0][0] for user in data[0:2, 0]]



[ripple_set[user][0][0] for user in data[:, 0]]

[[  0 454   0]
 [  0 442   0]
 [  0 349   1]
 ...
 [125 273   1]
 [125 165   1]
 [125  55   0]]
[454 442]
tensor([454, 442])


[[286,
  184,
  441,
  286,
  335,
  349,
  184,
  335,
  55,
  349,
  349,
  140,
  140,
  55,
  184,
  55,
  184,
  113,
  184,
  335,
  335,
  113,
  113,
  286,
  55,
  55,
  286,
  140,
  286,
  286,
  140,
  140]]

In [33]:
get_item_or_index('前端开发')

496

In [34]:
'''
    self,
    items: torch.LongTensor,
    labels: torch.LongTensor,
    memories_h: list,
    memories_r: list,
    memories_t: list,
'''

memories_h, memories_r, memories_t = [], [], []
# 路线
route1 = get_item_or_index('前端开发')
route2 = get_item_or_index('后端开发')
route3 = get_item_or_index('移动开发')
route4 = get_item_or_index('网络开发')
route5 = get_item_or_index('硬件开发')
route6 = get_item_or_index('游戏开发')
route7 = get_item_or_index('产品运维')
route8 = get_item_or_index('人工智能')
route9 = get_item_or_index('算法设计')
route10 = get_item_or_index('云计算')
route11 = get_item_or_index('计算机视觉')
idx2route = {0: '前端开发', 1:'后端开发',2:'移动开发',3:'网络开发', 4:'硬件开发',5:'游戏开发',6:'产品运维',7:'人工智能',8:'算法设计',9:'云计算',10:'计算机视觉'}
items = torch.LongTensor([route1, route2, route3,
                          route4, route5, route6,
                          route7, route8, route9,
                          route10, route11])  # 需要至少两个不然报错
labels = torch.LongTensor(np.zeros(len(items)))            # 要至少两个不然报错

# 给第一个用户测试
user = np.array([0,0,0,0,0,0,0,0,0,0,0])# 要至少两个不然报错
# user = np.array([10,10,10,10,10,10,10,10,10,10,10]) 

for i in range(args.n_hop):
        memories_h.append(torch.LongTensor([ripple_set[user][i][0] for user in user]))
        memories_r.append(torch.LongTensor([ripple_set[user][i][1] for user in user]))
        memories_t.append(torch.LongTensor([ripple_set[user][i][2] for user in user]))
if args.use_cuda:
    items = items.cuda()
    labels = labels.cuda()
    memories_h = list(map(lambda x: x.cuda(), memories_h))
    memories_r = list(map(lambda x: x.cuda(), memories_r))
    memories_t = list(map(lambda x: x.cuda(), memories_t))


# model(*get_feed_dict(args, model, test_data, ripple_set, args.batch_size))
return_dict = model(items, labels, memories_h, memories_r, memories_t)
scores = return_dict['scores'].cpu().detach().numpy()



In [36]:
import numpy as np

scores
# 对数组进行降序排序，并返回排序后的索引
idx = np.argsort(scores) [::-1]
# 输出排序后的概率和学习路线
for i in idx:
    print (f'概率：{scores [i]}, 路线：{idx2route[i]}')


概率：0.9999082088470459, 路线：前端开发
概率：0.9747733473777771, 路线：算法设计
概率：0.9510952830314636, 路线：游戏开发
概率：0.7395547032356262, 路线：人工智能
概率：0.6408618688583374, 路线：计算机视觉
概率：0.4610969126224518, 路线：硬件开发
概率：0.4316401183605194, 路线：移动开发
概率：0.26006683707237244, 路线：后端开发
概率：0.1043122336268425, 路线：产品运维
概率：0.012771104462444782, 路线：云计算
概率：0.005450739990919828, 路线：网络开发
